phase: fact
overwrite: True

dec_dict: meta/kor_decompose.json
content_font: "nanumgothic"
language: "kor"

C: 32
batch_size: 1
# gen
g_args:
  comp_enc:
    norm: "in"
    pad_type: zero
    sigmoid: True
  emb_block:
    emb_dim: 8
  dec:
    pad_type: zero
  content_enc:  # Content encoder
    norm: "in"
    C_out: 256
    content_sigmoid: False

# disc
d_args:
  pad_type: zero

# dset
# n_comps: 371
n_comps: 68

n_in_chars: 3
n_each_chars: 3
n_targets: 9

n_shots: 4

dset_aug:
  normalize: True
  random_affine: False
  
# AC
ac_args:
  norm: IN
  conv_dropout: 0.3
  clf_dropout: 0.2
  pad_type: zero

ac_w: 0.1
ac_gen_w: 0.1
dec_const_w: 1.
